version: '3'

services:

  app:
    container_name: app
    build:
      args:
        user: appuser
        uid: 1000
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - fruitorder

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fruitorder

  db:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
    - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - fruitorder
  
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    depends_on: 
      - db
    ports:
      - 8089:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}" 
    networks:
      - fruitorder

volumes:
  mysqldata:

networks:
  fruitorder:
    driver: bridge